#!/bin/sh

# parses and then returns the exaxt same code (formatted horribly)


#!/bin/sh

TOOLS_PATH="out"
ADDED_TO_PATH="lib/antlr-4.5.3-complete.jar:lib/scala-library.jar:${TOOLS_PATH}"

java -cp ${ADDED_TO_PATH} tool.ID
